import type { MDXComponents } from "mdx/types";
import { AlgorithmCard } from "@/components/learn/AlgorithmCard";
import { BuyMeCoffee } from "@/components/learn/BuyMeCoffee";
import { CompanyBoard } from "@/components/learn/CompanyBoard";
import { Contact } from "@/components/learn/Contact";
import { CrossSheetMap } from "@/components/learn/CrossSheetMap";
import { DataCampExercise } from "@/components/learn/DataCampExercise";
import { DrillDeck } from "@/components/learn/DrillDeck";
import { Figure } from "@/components/learn/Figure";
import { FileCode } from "@/components/learn/FileCode";
import { MathDrillDeck } from "@/components/learn/MathDrillDeck";
import { MockInterview } from "@/components/learn/MockInterview";
import { PhaseMap } from "@/components/learn/PhaseMap";
import { ProblemLadder } from "@/components/learn/ProblemLadder";
import { Quiz } from "@/components/learn/Quiz";
import { SheetTracker } from "@/components/learn/SheetTracker";
import { StudyPlanner } from "@/components/learn/StudyPlanner";
import { YoutuberCard } from "@/components/learn/YoutuberCard";
import { CardGrid, LinkCard } from "@/components/learn/StarlightPrimitives";
import { Callout, CalloutTitle, CalloutBody } from "@/components/learn/Aside";

/* Visualisation components, lazily loaded -- see components/learn/lazy-viz.tsx. */
import {
  AnimatedShinyText,
  ArrayStepper,
  AutodiffGraph,
  BorderBeam,
  ComplexityChart,
  DPTable,
  DSUView,
  DescentLab,
  EigenLab,
  ElimStepper,
  GraphTraversal,
  GridPathfinder,
  HeapView,
  HessianLab,
  IntervalTimeline,
  LinkedListRewire,
  Marquee,
  MatrixLab,
  Meteors,
  NormBall,
  NumberTicker,
  ProjectionLab,
  RecursionTree,
  SVDLab,
  SegmentTreeView,
  SpanExplorer,
  Spotlight,
  StackMachine,
  StateMachineView,
  SurfaceGrad,
  TaylorLab,
  TreeWalker,
  TrieView,
} from "@/components/learn/lazy-viz";

/**
 * Components available to every MDX page, without the page importing them.
 *
 * GENERATED by scripts/gen-mdx-components.mjs from
 * migration/mdx-component-list.json. Add a component there, not here.
 *
 * The Astro build required each page to import what it used, which is why
 * 1062 of the 1190 content files opened with an import line and a run of
 * `../`. Supplying them here let the migration delete those lines instead of
 * rewriting a thousand relative paths -- and an author adding a quiz to a new
 * page no longer counts directories.
 *
 * Five components carried almost all of that coupling: DataCampExercise (792
 * files), Quiz (595), Figure (292), FileCode (203), ProblemLadder (118).
 */
export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    AlgorithmCard,
    BuyMeCoffee,
    CompanyBoard,
    Contact,
    CrossSheetMap,
    DataCampExercise,
    DrillDeck,
    Figure,
    FileCode,
    MathDrillDeck,
    MockInterview,
    PhaseMap,
    ProblemLadder,
    Quiz,
    SheetTracker,
    StudyPlanner,
    YoutuberCard,
    CardGrid,
    LinkCard,
    Callout,
    CalloutTitle,
    CalloutBody,
    AnimatedShinyText,
    ArrayStepper,
    AutodiffGraph,
    BorderBeam,
    ComplexityChart,
    DPTable,
    DSUView,
    DescentLab,
    EigenLab,
    ElimStepper,
    GraphTraversal,
    GridPathfinder,
    HeapView,
    HessianLab,
    IntervalTimeline,
    LinkedListRewire,
    Marquee,
    MatrixLab,
    Meteors,
    NormBall,
    NumberTicker,
    ProjectionLab,
    RecursionTree,
    SVDLab,
    SegmentTreeView,
    SpanExplorer,
    Spotlight,
    StackMachine,
    StateMachineView,
    SurfaceGrad,
    TaylorLab,
    TreeWalker,
    TrieView,
    /* content uses <Youtuber> for YoutuberCard */
    Youtuber: YoutuberCard,
    ...components,
  };
}

export default getMDXComponents;
