/**
 * Translations for the hand-written sidebar group labels in `astro.config.mjs`.
 *
 * Starlight translates its own chrome (search, ToC, pagination, …) for 36
 * locales out of the box, and autogenerated page titles come from each page's
 * frontmatter. What it cannot know is the label you invented for a group, so
 * every `{ label: '…' }` in the sidebar config needs its own `translations`
 * map or the group heading stays English in every locale.
 *
 * Rather than inline four extra strings at 44 call sites, the labels live here
 * keyed by their English text and `withSidebarTranslations()` walks the config
 * injecting them. Adding a language = adding one property per entry.
 *
 * Keys MUST match the English `label` in `astro.config.mjs` exactly.
 */

type LabelTranslations = Record<string, string>;

/**
 * Product and algorithm names (Python, Flask, NumPy, DSA, CP, OOD) are left
 * untranslated on purpose -- they are the terms readers search for, and
 * localising them makes technical docs harder to scan, not easier.
 */
export const SIDEBAR_LABELS: Record<string, LabelTranslations> = {
	// --- Top-level sections -------------------------------------------------
	Guides: { 'zh-CN': '指南', hi: 'गाइड', es: 'Guías', ja: 'ガイド' },
	Tutorials: { 'zh-CN': '教程', hi: 'ट्यूटोरियल', es: 'Tutoriales', ja: 'チュートリアル' },
	'Flask Tutorials': {
		'zh-CN': 'Flask 教程',
		hi: 'Flask ट्यूटोरियल',
		es: 'Tutoriales de Flask',
		ja: 'Flask チュートリアル',
	},
	'Python Automation and Scripting': {
		'zh-CN': 'Python 自动化与脚本',
		hi: 'Python ऑटोमेशन और स्क्रिप्टिंग',
		es: 'Automatización y scripting con Python',
		ja: 'Python 自動化とスクリプティング',
	},
	'Data Analytics': {
		'zh-CN': '数据分析',
		hi: 'डेटा एनालिटिक्स',
		es: 'Análisis de datos',
		ja: 'データ分析',
	},
	'Mathematics for Machine Learning': {
		'zh-CN': '机器学习数学',
		hi: 'मशीन लर्निंग के लिए गणित',
		es: 'Matemáticas para machine learning',
		ja: '機械学習のための数学',
	},
	'Machine Learning': {
		'zh-CN': '机器学习',
		hi: 'मशीन लर्निंग',
		es: 'Machine learning',
		ja: '機械学習',
	},
	'Deep Learning': {
		'zh-CN': '深度学习',
		hi: 'डीप लर्निंग',
		es: 'Deep learning',
		ja: 'ディープラーニング',
	},
	'DSA with Python': {
		'zh-CN': 'Python 数据结构与算法',
		hi: 'Python के साथ DSA',
		es: 'Estructuras de datos y algoritmos con Python',
		ja: 'Python によるデータ構造とアルゴリズム',
	},
	'Software Testing and Quality': {
		'zh-CN': '软件测试与质量',
		hi: 'सॉफ़्टवेयर टेस्टिंग और गुणवत्ता',
		es: 'Pruebas y calidad de software',
		ja: 'ソフトウェアテストと品質',
	},
	Projects: { 'zh-CN': '项目', hi: 'प्रोजेक्ट्स', es: 'Proyectos', ja: 'プロジェクト' },
	Reference: { 'zh-CN': '参考', hi: 'संदर्भ', es: 'Referencia', ja: 'リファレンス' },

	// --- DSA sub-groups -----------------------------------------------------
	'Start Here': {
		'zh-CN': '从这里开始',
		hi: 'यहाँ से शुरू करें',
		es: 'Empieza aquí',
		ja: 'ここから始める',
	},
	Foundations: { 'zh-CN': '基础', hi: 'बुनियादी बातें', es: 'Fundamentos', ja: '基礎' },
	'Interview Patterns': {
		'zh-CN': '面试题型',
		hi: 'इंटरव्यू पैटर्न',
		es: 'Patrones de entrevista',
		ja: '面接パターン',
	},
	'Advanced & Competitive': {
		'zh-CN': '进阶与竞赛',
		hi: 'एडवांस्ड और कॉम्पिटिटिव',
		es: 'Avanzado y competitivo',
		ja: '応用と競技',
	},
	'Reference & Strategy': {
		'zh-CN': '参考与策略',
		hi: 'संदर्भ और रणनीति',
		es: 'Referencia y estrategia',
		ja: 'リファレンスと戦略',
	},
	'Company Guides': {
		'zh-CN': '公司指南',
		hi: 'कंपनी गाइड',
		es: 'Guías por empresa',
		ja: '企業別ガイド',
	},
	'Low-Level Design': {
		'zh-CN': '低层设计',
		hi: 'लो-लेवल डिज़ाइन',
		es: 'Diseño de bajo nivel',
		ja: '低レベル設計',
	},
	Concurrency: { 'zh-CN': '并发', hi: 'कनकरेंसी', es: 'Concurrencia', ja: '並行処理' },

	// --- DSA phases ---------------------------------------------------------
	// The `NN ·` prefix is a sort key, not prose, so it is preserved verbatim.
	'00 · Start Here': {
		'zh-CN': '00 · 从这里开始',
		hi: '00 · यहाँ से शुरू करें',
		es: '00 · Empieza aquí',
		ja: '00 · ここから始める',
	},
	'01 · Foundations': {
		'zh-CN': '01 · 基础',
		hi: '01 · बुनियादी बातें',
		es: '01 · Fundamentos',
		ja: '01 · 基礎',
	},
	'02 · Python for DSA & CP': {
		'zh-CN': '02 · 用于 DSA 与 CP 的 Python',
		hi: '02 · DSA और CP के लिए Python',
		es: '02 · Python para DSA y CP',
		ja: '02 · DSA・CP のための Python',
	},
	'03 · Core Data Structures': {
		'zh-CN': '03 · 核心数据结构',
		hi: '03 · मुख्य डेटा स्ट्रक्चर',
		es: '03 · Estructuras de datos básicas',
		ja: '03 · 基本データ構造',
	},
	'04 · Sorting & Searching': {
		'zh-CN': '04 · 排序与查找',
		hi: '04 · सॉर्टिंग और सर्चिंग',
		es: '04 · Ordenación y búsqueda',
		ja: '04 · ソートと探索',
	},
	'05 · Arrays & Strings': {
		'zh-CN': '05 · 数组与字符串',
		hi: '05 · ऐरे और स्ट्रिंग',
		es: '05 · Arrays y cadenas',
		ja: '05 · 配列と文字列',
	},
	'06 · Search & Selection': {
		'zh-CN': '06 · 搜索与选择',
		hi: '06 · सर्च और सिलेक्शन',
		es: '06 · Búsqueda y selección',
		ja: '06 · 探索と選択',
	},
	'07 · Intervals & Greedy': {
		'zh-CN': '07 · 区间与贪心',
		hi: '07 · इंटरवल और ग्रीडी',
		es: '07 · Intervalos y voraces',
		ja: '07 · 区間と貪欲法',
	},
	'08 · Linked Lists': {
		'zh-CN': '08 · 链表',
		hi: '08 · लिंक्ड लिस्ट',
		es: '08 · Listas enlazadas',
		ja: '08 · 連結リスト',
	},
	'09 · Trees': { 'zh-CN': '09 · 树', hi: '09 · ट्री', es: '09 · Árboles', ja: '09 · 木' },
	'10 · Graphs': { 'zh-CN': '10 · 图', hi: '10 · ग्राफ़', es: '10 · Grafos', ja: '10 · グラフ' },
	'11 · Recursion & Backtracking': {
		'zh-CN': '11 · 递归与回溯',
		hi: '11 · रिकर्शन और बैकट्रैकिंग',
		es: '11 · Recursión y backtracking',
		ja: '11 · 再帰とバックトラッキング',
	},
	'12 · Dynamic Programming': {
		'zh-CN': '12 · 动态规划',
		hi: '12 · डायनामिक प्रोग्रामिंग',
		es: '12 · Programación dinámica',
		ja: '12 · 動的計画法',
	},
	'13 · Bit Manipulation & Math': {
		'zh-CN': '13 · 位运算与数学',
		hi: '13 · बिट मैनिपुलेशन और गणित',
		es: '13 · Bits y matemáticas',
		ja: '13 · ビット演算と数学',
	},
	'14 · Design Problems': {
		'zh-CN': '14 · 设计题',
		hi: '14 · डिज़ाइन प्रॉब्लम्स',
		es: '14 · Problemas de diseño',
		ja: '14 · 設計問題',
	},
	'15 · Simulation & Implementation': {
		'zh-CN': '15 · 模拟与实现',
		hi: '15 · सिमुलेशन और इम्प्लीमेंटेशन',
		es: '15 · Simulación e implementación',
		ja: '15 · シミュレーションと実装',
	},
	'16 · Advanced Graph Algorithms': {
		'zh-CN': '16 · 高级图算法',
		hi: '16 · एडवांस्ड ग्राफ़ एल्गोरिदम',
		es: '16 · Algoritmos de grafos avanzados',
		ja: '16 · 高度なグラフアルゴリズム',
	},
	'17 · Advanced CP Topics': {
		'zh-CN': '17 · 进阶竞赛主题',
		hi: '17 · एडवांस्ड CP विषय',
		es: '17 · Temas avanzados de CP',
		ja: '17 · 応用 CP トピック',
	},
	'18 · Templates & Cheatsheets': {
		'zh-CN': '18 · 模板与速查表',
		hi: '18 · टेम्प्लेट और चीटशीट',
		es: '18 · Plantillas y chuletas',
		ja: '18 · テンプレートとチートシート',
	},
	'19 · Interview & Contest Strategy': {
		'zh-CN': '19 · 面试与比赛策略',
		hi: '19 · इंटरव्यू और कॉन्टेस्ट रणनीति',
		es: '19 · Estrategia de entrevistas y concursos',
		ja: '19 · 面接・コンテスト戦略',
	},
	'20 · Problem Sets': {
		'zh-CN': '20 · 题集',
		hi: '20 · प्रॉब्लम सेट',
		es: '20 · Conjuntos de problemas',
		ja: '20 · 問題集',
	},
	'21 · Company Guides': {
		'zh-CN': '21 · 公司指南',
		hi: '21 · कंपनी गाइड',
		es: '21 · Guías por empresa',
		ja: '21 · 企業別ガイド',
	},
	'22 · Low-Level Design (OOD)': {
		'zh-CN': '22 · 低层设计（OOD）',
		hi: '22 · लो-लेवल डिज़ाइन (OOD)',
		es: '22 · Diseño de bajo nivel (OOD)',
		ja: '22 · 低レベル設計 (OOD)',
	},
	'23 · Concurrency': {
		'zh-CN': '23 · 并发',
		hi: '23 · कनकरेंसी',
		es: '23 · Concurrencia',
		ja: '23 · 並行処理',
	},
};

/** Labels present in the config but missing from the table above. */
export const untranslatedLabels: string[] = [];

/**
 * Walk a Starlight sidebar config and attach a `translations` map to every
 * entry whose `label` appears in {@link SIDEBAR_LABELS}. Returns a new array;
 * the input is not mutated. Any label without an entry is recorded in
 * {@link untranslatedLabels} so the config can warn instead of silently
 * shipping an English heading to Japanese readers.
 */
export function withSidebarTranslations<T>(sidebar: T): T {
	const walk = (node: any): any => {
		if (Array.isArray(node)) return node.map(walk);
		if (!node || typeof node !== 'object') return node;

		const next: Record<string, unknown> = { ...node };
		if (typeof next.label === 'string') {
			const translations = SIDEBAR_LABELS[next.label];
			if (translations) next.translations = { ...translations };
			else if (!untranslatedLabels.includes(next.label)) {
				untranslatedLabels.push(next.label);
				console.warn(
					`[i18n] Sidebar label "${next.label}" has no translations; ` +
						'add it to SIDEBAR_LABELS in src/i18n/sidebar-labels.ts.'
				);
			}
		}
		if (Array.isArray(next.items)) next.items = next.items.map(walk);
		return next;
	};

	return walk(sidebar) as T;
}
