"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  read,
  subscribe,
  getLastPage,
  currentStreak,
  unenrol,
  type ProgressState,
} from "@/src/lib/progress/local";
import { moduleOf } from "@/src/lib/progress/ids";
import { tally, levelFor } from "@/src/lib/progress/awards";
import { readHint } from "@/src/lib/auth/hint";
import NumberTicker from "@/src/components/react/NumberTicker";
import { t } from "@/lib/strings";

/**
 * Everything the learner has done so far.
 *
 * Reads the local progress store first, so the page is useful instantly and
 * without an account. If there is a signed-in session it then reconciles with
 * the cloud copy and repaints. Module totals come from
 * public/progress-manifest.json, generated by scripts/gen-progress-manifest.mjs.
 *
 * Layout note: the prompt markers down the left sit in one fixed gutter, so
 * they line up into a single column the way prompts do in a REPL session.
 * Keep new rows on that grid.
 */
interface ManifestModule {
  slug: string;
  label: string;
  count: number;
  hasExam?: boolean;
  /** Where the module opens. `/<slug>/` is a folder, not a page. */
  entry?: string;
  /** Set for catalogued courses, which have a course page. */
  course?: boolean;
  href?: string;
}

/**
 * Badge labels, spelled out rather than built from the badge id.
 *
 * Looking the key up from the badge id would work at runtime, but
 * `scripts/check-i18n.mjs` reads source for literal translation calls -- so
 * nine live keys were reported as unused, which is exactly the signal that
 * check exists to give.
 */
const BADGE_LABELS: Record<string, string> = {
  FirstPage: t("pch.badgeFirstPage"),
  TenPages: t("pch.badgeTenPages"),
  FiftyPages: t("pch.badgeFiftyPages"),
  HundredPages: t("pch.badgeHundredPages"),
  Quizzer: t("pch.badgeQuizzer"),
  WeekStreak: t("pch.badgeWeekStreak"),
  MonthStreak: t("pch.badgeMonthStreak"),
  ModuleDone: t("pch.badgeModuleDone"),
  Certified: t("pch.badgeCertified"),
};

/** Turn "tutorials/python-lists/list-slicing" into "List slicing". */
function titleOf(pageId: string): string {
  const last = pageId.split("/").pop() ?? pageId;
  const words = last.replace(/-/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function Dashboard() {
  const [state, setState] = useState<ProgressState | null>(null);
  const [manifest, setManifest] = useState<ManifestModule[]>([]);
  /** Only the server issues certificates, so a guest always has zero. */
  const [certificates, setCertificates] = useState(0);
  const [notice, setNotice] = useState<string | null>(null);
  const [account, setAccount] = useState(false);
  const [syncing, setSyncing] = useState(false);

  // localStorage is not readable while rendering on the server, so the first
  // client render is what fills these in.
  useEffect(() => {
    setState(read());
    setAccount(Boolean(readHint() && !readHint()?.anon));
    return subscribe(setState);
  }, []);

  useEffect(() => {
    let cancelled = false;

    void (async () => {
      try {
        const res = await fetch("/progress-manifest.json");
        if (res.ok && !cancelled) {
          setManifest(((await res.json()).modules ?? []) as ManifestModule[]);
        }
      } catch {
        /* the page still works without module totals */
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  /**
   * Reconcile with the cloud copy, once, for a real account.
   *
   * Guests are complete as they are: their progress lives in this browser and
   * there is nothing to reconcile with. The page says so plainly and offers
   * the upgrade rather than silently showing a device-local view.
   */
  useEffect(() => {
    const hint = readHint();
    if (!hint || hint.anon) {
      setNotice(t("pch.dashLocalOnly"));
      return;
    }

    let cancelled = false;

    void (async () => {
      setNotice(t("pch.dashSyncing"));
      try {
        const { hydrateOnce } = await import("@/src/lib/progress/sync");
        const merged = await hydrateOnce();
        const held = await countCertificates();
        if (cancelled) return;
        setState(merged);
        setCertificates(held);
        setNotice(t("pch.dashSynced"));
      } catch (err) {
        console.warn("[dashboard] sync failed:", err);
        if (!cancelled) setNotice(null);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  async function resync() {
    setSyncing(true);
    try {
      const { resync: pull } = await import("@/src/lib/progress/sync");
      setState(await pull());
      setNotice(t("pch.dashSynced"));
    } catch (err) {
      // Used to fail silently, with an unhandled rejection.
      console.warn("[dashboard] resync failed:", err);
      setNotice(t("pch.authErrNetwork"));
    } finally {
      setSyncing(false);
    }
  }

  if (!state) return <p className="app__loading">{t("pch.authLoading")}</p>;

  const completed = Object.values(state.modules).reduce(
    (n, list) => n + list.length,
    0,
  );
  const counts = Object.fromEntries(manifest.map((m) => [m.slug, m.count]));
  const score = tally(state, counts, certificates);
  const { level, into, span } = levelFor(score.xp);
  const last = getLastPage();

  const renderCourse = (mod: ManifestModule, removable = false) => {
          const done = (state.modules[mod.slug] ?? []).length;
          // Guard against a page renamed since its id was stored: a stale id
          // would otherwise push the bar past 100%.
          const pct = mod.count
            ? Math.min(100, Math.round((done / mod.count) * 100))
            : 0;

          return (
            <li
              className="pch-dash__module"
              key={mod.slug}
              data-started={String(done > 0)}
            >
              <span
                className="pch-prompt"
                aria-hidden="true"
                data-state={pct === 100 ? "done" : done > 0 ? "started" : ""}
              />
              <Link
                className="pch-dash__module-name"
                href={mod.href ?? mod.entry ?? `/${mod.slug}/`}
              >
                {mod.label}
              </Link>
              <span className="pch-dash__module-count">
                {`${done} / ${mod.count} ${t("pch.dashPages")}`}
              </span>
              <span className="pch-dash__bar">
                <span
                  className="pch-dash__bar-fill"
                  style={{ "--pch-fill": `${pct}%` } as React.CSSProperties}
                />
              </span>

              {/* The exam link shows whenever a module has one. Sitting it
                  early is allowed -- only the certificate needs 90% of the
                  pages, and the server says so if they claim too soon. */}
              {mod.hasExam || removable ? (
                <span className="pch-dash__module-actions">
                  {mod.hasExam ? (
                    <Link
                      className="pch-dash__module-exam"
                      href={`/exam/${mod.slug}/`}
                    >
                      {t("pch.dashExam")}
                    </Link>
                  ) : null}
                  {removable ? (
                    <button
                      type="button"
                      className="pch-dash__module-remove"
                      onClick={() => unenrol(mod.slug)}
                      aria-label={`Remove ${mod.label} from your courses`}
                    >
                      Remove
                    </button>
                  ) : null}
                </span>
              ) : null}
            </li>
          );
  };

  const courses = manifest.filter((mod) => mod.course);
  const enrolled = state.enrolled ?? [];
  const taken = (mod: ManifestModule) => enrolled.includes(mod.slug);
  // Keep the learner's own order: the course they took up first stays first.
  const mine = courses
    .filter(taken)
    .sort(
      (a, b) =>
        (enrolled.indexOf(a.slug) + 1 || 999) - (enrolled.indexOf(b.slug) + 1 || 999),
    );
  const others = courses.filter((mod) => !taken(mod));

  const stats = [
    { key: "streak", value: currentStreak(state), label: t("pch.dashStreak") },
    {
      key: "longest",
      value: state.streak.longest,
      label: t("pch.dashLongest"),
    },
    { key: "completed", value: completed, label: t("pch.dashCompleted") },
    {
      key: "quizzes",
      value: Object.keys(state.quizzes).length,
      label: t("pch.dashQuizzes"),
    },
  ];

  return (
    <div className="pch-dash pch-dash--ready">
      {notice ? <p className="pch-dash__notice">{notice}</p> : null}

      {last ? (
        <section>
          <h2>{t("pch.dashContinue")}</h2>
          <Link className="pch-dash__continue" href={last.href}>
            <span
              className="pch-prompt"
              data-state="started"
              aria-hidden="true"
            />
            <span className="pch-dash__continue-module">
              {manifest.find((m) => m.slug === moduleOf(last.pageId))?.label ??
                moduleOf(last.pageId).replace(/-/g, " ")}
            </span>
            <span className="pch-dash__continue-title">
              {last.title || titleOf(last.pageId)}
            </span>
          </Link>
        </section>
      ) : null}

      <ul className="pch-dash__stats">
        {stats.map((stat) => (
          <li key={stat.key} data-key={stat.key}>
            {/* Counts up once, the first time the card is seen. The number
                arriving is the point of a progress page; it parks after that
                and reduced motion skips straight to the value. */}
            <strong>
              <NumberTicker value={stat.value} />
            </strong>
            <span>{stat.label}</span>
          </li>
        ))}
      </ul>

      <section className="pch-level">
        <p className="pch-level__line">
          <span className="pch-level__num">{level}</span>
          <span className="pch-level__label">{t("pch.levelLabel")}</span>
          <span className="pch-level__xp">{`${score.xp} ${t("pch.levelXp")}`}</span>
        </p>
        <span className="pch-dash__bar">
          <span
            className="pch-dash__bar-fill"
            style={
              {
                "--pch-fill": `${Math.round((into / span) * 100)}%`,
              } as React.CSSProperties
            }
          />
        </span>
      </section>

      <h2>{t("pch.badgesTitle")}</h2>
      <ul className="pch-badges">
        {score.badges.map((badge) => (
          <li
            key={badge.id}
            className="pch-badge"
            data-earned={String(badge.earned)}
            /* Locked badges still show their target, so the list reads as a
               set of things to aim at rather than a wall of blanks. */
            title={`${badge.have} / ${badge.need}`}
          >
            {BADGE_LABELS[badge.id] ?? badge.id}
          </li>
        ))}
      </ul>

      <h2>{t("pch.dashModules")}</h2>
      {completed === 0 ? (
        <p className="pch-dash__empty">{t("pch.dashNoProgress")}</p>
      ) : null}
      {/* Courses taken up (started, or a lesson finished) come first; the
          rest of the catalogue folds away underneath. */}
      <ul className="pch-dash__modules">
        {mine.map((mod) => renderCourse(mod, true))}
      </ul>
      {mine.length === 0 ? (
        <p className="pch-dash__empty">
          <Link href="/welcome/">Pick a goal</Link> and we&rsquo;ll add the courses for it,
          or <Link href="/courses/">browse every course</Link>.
        </p>
      ) : null}
      {others.length ? (
        <details className="pch-dash__more">
          <summary>More courses ({others.length})</summary>
          <ul className="pch-dash__modules">
            {others.map((mod) => renderCourse(mod))}
          </ul>
        </details>
      ) : null}

      <h2>
        {t("pch.dashBookmarks")}{" "}
        <Link className="pch-dash__more-link" href="/saved/">
          All saved →
        </Link>
      </h2>
      {state.bookmarks.length === 0 ? (
        <p className="pch-dash__empty">{t("pch.dashNoBookmarks")}</p>
      ) : null}
      <ul className="pch-dash__bookmarks">
        {state.bookmarks.map((pageId) => (
          <li key={pageId}>
            <span className="pch-prompt" aria-hidden="true" />
            <Link href={`/${pageId}/`}>{titleOf(pageId)}</Link>
          </li>
        ))}
      </ul>

      {/* Private notes, gathered in one place. They were only visible on the
          lesson each was written on, so finding one meant remembering where. */}
      <h2>Your notes</h2>
      {Object.keys(state.notes).length === 0 ? (
        <p className="pch-dash__empty">
          No notes yet. Use “Add a private note” at the end of any lesson; only you can
          see them.
        </p>
      ) : (
        <ul className="pch-dash__notes">
          {Object.entries(state.notes).map(([pageId, body]) => (
            <li key={pageId}>
              <Link href={`/${pageId}/`}>{titleOf(pageId)}</Link>
              <p>{body.length > 180 ? `${body.slice(0, 180).trimEnd()}…` : body}</p>
            </li>
          ))}
        </ul>
      )}

      <p className="pch-dash__actions">
        {account ? (
          <button
            type="button"
            className="pch-auth__secondary"
            disabled={syncing}
            onClick={() => void resync()}
          >
            {t("pch.dashResync")}
          </button>
        ) : (
          <Link className="pch-auth__secondary" href="/login/?next=/dashboard/">
            {t("pch.authSignIn")}
          </Link>
        )}
      </p>
    </div>
  );
}

/** How many certificates this learner holds, from their own index doc. */
async function countCertificates(): Promise<number> {
  try {
    const { currentUser } = await import("@/src/lib/firebase/auth");
    const user = await currentUser();
    if (!user || user.isAnonymous) return 0;

    const { doc, getDoc } = await import("firebase/firestore");
    const { getDb } = await import("@/src/lib/firebase/client");
    const snap = await getDoc(
      doc(await getDb(), "users", user.uid, "stats", "certificates"),
    );
    return ((snap.data()?.items ?? []) as unknown[]).length;
  } catch {
    return 0;
  }
}

export default Dashboard;
