"use client";

/*
 * GENERATED by scripts/gen-mdx-components.mjs. Do not edit by hand.
 *
 * One next/dynamic wrapper per visualisation, so a lesson downloads only the
 * visualisations it renders. See the note in the generator for why this has
 * to be a client module.
 */
import dynamic from "next/dynamic";

export const AnimatedShinyText = dynamic(() => import("@/src/components/react/AnimatedShinyText"));
export const ArrayStepper = dynamic(() => import("@/src/components/viz/ArrayStepper"));
export const AutodiffGraph = dynamic(() => import("@/src/components/viz/math/AutodiffGraph"));
export const BorderBeam = dynamic(() => import("@/src/components/react/BorderBeam"));
export const ComplexityChart = dynamic(() => import("@/src/components/viz/ComplexityChart"));
export const DPTable = dynamic(() => import("@/src/components/viz/DPTable"));
export const DSUView = dynamic(() => import("@/src/components/viz/DSUView"));
export const DescentLab = dynamic(() => import("@/src/components/viz/math/DescentLab"));
export const EigenLab = dynamic(() => import("@/src/components/viz/math/EigenLab"));
export const ElimStepper = dynamic(() => import("@/src/components/viz/math/ElimStepper"));
export const GraphTraversal = dynamic(() => import("@/src/components/viz/GraphTraversal"));
export const GridPathfinder = dynamic(() => import("@/src/components/viz/GridPathfinder"));
export const HeapView = dynamic(() => import("@/src/components/viz/HeapView"));
export const HessianLab = dynamic(() => import("@/src/components/viz/math/HessianLab"));
export const IntervalTimeline = dynamic(() => import("@/src/components/viz/IntervalTimeline"));
export const LinkedListRewire = dynamic(() => import("@/src/components/viz/LinkedListRewire"));
export const Marquee = dynamic(() => import("@/src/components/react/Marquee"));
export const MatrixLab = dynamic(() => import("@/src/components/viz/math/MatrixLab"));
export const Meteors = dynamic(() => import("@/src/components/react/Meteors"));
export const NormBall = dynamic(() => import("@/src/components/viz/math/NormBall"));
export const NumberTicker = dynamic(() => import("@/src/components/react/NumberTicker"));
export const ProjectionLab = dynamic(() => import("@/src/components/viz/math/ProjectionLab"));
export const RecursionTree = dynamic(() => import("@/src/components/viz/RecursionTree"));
export const SVDLab = dynamic(() => import("@/src/components/viz/math/SVDLab"));
export const SegmentTreeView = dynamic(() => import("@/src/components/viz/SegmentTreeView"));
export const SpanExplorer = dynamic(() => import("@/src/components/viz/math/SpanExplorer"));
export const Spotlight = dynamic(() => import("@/src/components/react/Spotlight"));
export const StackMachine = dynamic(() => import("@/src/components/viz/StackMachine"));
export const StateMachineView = dynamic(() => import("@/src/components/viz/StateMachineView"));
export const SurfaceGrad = dynamic(() => import("@/src/components/viz/math/SurfaceGrad"));
export const TaylorLab = dynamic(() => import("@/src/components/viz/math/TaylorLab"));
export const TreeWalker = dynamic(() => import("@/src/components/viz/TreeWalker"));
export const TrieView = dynamic(() => import("@/src/components/viz/TrieView"));
